name: RolePlay
main: awzaw\roleplay\Main
version: 1.1.0-5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD
author: awzaw
website: https://github.com/awzaw
commands:
 rp:
  description: "Join the server RP"
  usage: "/rp"
  permission: roleplay
permissions:
  roleplay:
    description: "Allows RP toggle on/off"
    default: true